### PR TITLE
Fix sidebar format again

### PR DESCRIPTION
**Pull request by AlexKnauth**

### CODE REVIEW

**Comment by AlexKnauth** [comment]
I was just wondering, when does the website normally update after the repo changes?

**Comment by michaelklishin** [comment]
When I deploy it. Will do in a bit.

**Comment by AlexKnauth** [comment]
Ok

**Comment by AlexKnauth** [comment]
The sidebar problem is still there. Did you deploy it?

**Comment by michaelklishin** [comment]
Just did.

**Comment by AlexKnauth** [comment]
Thanks!

**Pull request merged**
