### PR TITLE
Added book: Clojure Standard Library (annotated guide)

### PR DESCRIPTION
**Pull request by reborg**
Added new book, I'm the author. The book is still in Early Access, not sure if applicable to the guides.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Early access is OK, thank you!

**Comment by reborg** [comment]
Nice, thank you :) Just remembered that my VIM kills additional spaces at the end of the line. Let me know if that's a problem, there are changed lines other than the ones with the book.

**Comment by seancorfield** [comment]
You can ask GitHub to show you a diff with whitespace ignored:

https://github.com/clojuredocs/guides/pull/232/files?w=1

(and as far as I'm concerned all whitespace at the end of lines should be taken out and shot! :) )

**Comment by reborg** [comment]
@seancorfield good to know. Depending on the context it might be desirable or not. It happened a few times that I mistakenly saved core.clj in clojure without changes... well, it comes back full of them :D

**Pull request merged**
